/**
 * An Accept activity, mostly used for accepting follow requests.
 * These are automatically generated by groups, because groups are
 * only relays that accept all followers.
 *
 * @export
 * @class AcceptActivity
 */
export class AcceptActivity {
    '@context': string | object | Array<string | object>;
    type: 'Accept';

    // The actor doing the aceepting
    actor: string | object;
    
    // The object (such as a follow request) that is being accepted
    object: string | object;

    [key: string]: any;
}